### ISSUE TITLE
./cam.go:60:22: undefined: camConstants.CamModuleTypeLib

### ISSUE THREAD

**Issue by scottstensland** [go-cam/cam#1]
```

git clone git@github.com:go-cam/cam.git

cd /home/pie/src/gopath/src/github.com/go-cam/cam

go mod tidy

go install

# github.com/go-cam/cam/component/camHttp
component/camHttp/HttpComponent.go:216:20: undefined: syscall.ERROR_FILE_NOT_FOUND

................  so then I tried your doc on howto install

https://github.com/go-cam/cam-doc/blob/master/Installation/Installation.md

git clone --depth=1 https://github.com/go-cam/cam-template.git   

cd cam-template

go mod tidy

go build cam.go
# command-line-arguments
./cam.go:60:22: undefined: camConstants.CamModuleTypeLib
./cam.go:66:22: undefined: camConstants.CamModuleTypeApp
./cam.go:83:21: undefined: camConstants.CamModuleTypeApp

```

**Comment by go-cam** [comment]
The doc it too old.   I will update the new documents when the official version of 0.3.0 is released. Because I used this project by myself, changed a lot of things, and didn&#39;t document them in time



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Scott&nbsp;Stensland"; 
发送时间: 2020年3月8日(星期天) 晚上8:02
收件人: "go-cam/cam";
抄送: "Subscribed";
主题: [go-cam/cam] ./cam.go:60:22: undefined: camConstants.CamModuleTypeLib (#1)




git clone git@github.com:go-cam/cam.git
 
cd /home/pie/src/gopath/src/github.com/go-cam/cam
 
go mod tidy
 
go install
 
github.com/go-cam/cam/component/camHttp
 
component/camHttp/HttpComponent.go:216:20: undefined: syscall.ERROR_FILE_NOT_FOUND
 
................  so then I tried your doc on howto install
 
https://github.com/go-cam/cam-doc/blob/master/Installation/Installation.md
 
git clone --depth=1 https://github.com/go-cam/cam-template.git
 
cd cam-template
 
go mod tidy
 go build cam.go # command-line-arguments ./cam.go:60:22: undefined: camConstants.CamModuleTypeLib ./cam.go:66:22: undefined: camConstants.CamModuleTypeApp ./cam.go:83:21: undefined: camConstants.CamModuleTypeApp  
&mdash;

**Comment by cinling** [comment]
now is active in v0.3.0-beta.1
